### ISSUE TITLE
Clicking on accessed services will result in error if the consent feature in EB is disabled

### ISSUE THREAD

**Issue by ArnoutvdKnaap** [OpenConext/OpenConext-profile#255]
EB API will return a 404 when asked for consent if the feature is disabled. This will return a symfony error in profile

**Comment by thijskh** [comment]
This is correct. Profile uses the consent information to be able to show which service providers you logged into. What would you expect to happen?

**Comment by ArnoutvdKnaap** [comment]
I expected to see a blank page or not available instead of a symfony crash report

**Comment by thijskh** [comment]
This is what the user sees:

![Onverwachte fout. Er ging iets mis. Probeer het opnieuw, of neem contact op met support als het probleem aanhoudt](https://user-images.githubusercontent.com/3808792/208095166-2c950dbc-c013-4c82-9cff-080eb8743e85.png)

This is currently logged: `OpenConext\EngineBlockApiClientBundle\Exception\ResourceNotFoundException: "Resource "consent/urn%3Acollab%3Aperson%3Aexample.com%3Aadmin" not found"`

I can add to that exception message something like "Is Engineblocks consent feature enabled?"

Logging should suffice I think - I don't think it's worthwhile to add a specific end user facing message in this case since it's only the admin that can resolve this?

**Comment by ArnoutvdKnaap** [comment]
Am I doing something wrong than? Because i get this message:
![image](https://user-images.githubusercontent.com/12121158/208096400-0db947e8-dae6-45c1-a4af-0e5fe9559f5a.png)

**Comment by thijskh** [comment]
It's the same message but you're running the application in development mode.

**Comment by ArnoutvdKnaap** [comment]
Ah i see. That is a lot better yes. :D
